#ifndef FT_CONF_OBJ_H
# define FT_CONF_OBJ_H
/*
** CONFIG DE LA POSITION DES OBJET ET CLIC OBJET
*/

/*
** BLOC CYCLE MANAGEMENT
*/
# define BARCTDSIZE 310
# define BARCTDLEFTX 1543
# define BARCTDLEFTY 275

# define BTNCTDPLUSX1 1504
# define BTNCTDPLUSX2 1534
# define BTNCTDPLUSY1 276
# define BTNCTDPLUSY2 298
# define BTNCTDPLUS1X 1496
# define BTNCTDPLUS1Y 268

# define BTNCTDLESSINCREMENT 360
# define BTNCTDLESSX1 BTNCTDPLUSX1 + BTNCTDLESSINCREMENT
# define BTNCTDLESSX2 BTNCTDPLUSX2 + BTNCTDLESSINCREMENT
# define BTNCTDLESSY1 276
# define BTNCTDLESSY2 298
# define BTNCTDLESS1X BTNCTDPLUS1X + BTNCTDLESSINCREMENT
# define BTNCTDLESS1Y 268


#endif
